name: AutoCheck

on:
  workflow_dispatch:

  schedule:
    - cron: 0 0 * * * 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout codes'
      uses: actions/checkout@v1
    - name: 'Set up Python'
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'

    - name: 'Install requirements'
      run: |
        pip3 install requests pycryptodome
    
    - name: Run
      run: |
        python3 main.py <<EOF
        ${{secrets.USERS}}
        EOF
