name: "AutoCheck"

on:
  workflow_dispatch:
  
  # schedule:
  #    - cron: 0 16 * * *
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip3 install requests pycryptodome
        
    - name: AutoCheck
      run: |
        python3 main.py <<EOF
        ${{secrets.USERS}}
        EOF
