name: "sendSMS"

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip3 install requests pycryptodome

    - name: send SMS
      run: |
          python3 SMS.py send
      env:
        USERNAME: ${{ secrets.USERNAME }}
        DEVICE_SEED: ${{ secrets.DEVICE_SEED }}